server:
  port: 8080

spring:
  application:
    name: Springoteka

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    path: /api



